name: "Build"
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v18
    - name: "Run nix flake check"
      run: nix flake check
    - name: "Run nix build"
      run: nix build -L .#fiber{,-lwt,_4_08,_4_09,_4_10,_4_11,_4_12,_4_13,_4_14,_5_0,5_1}
